"""Sample clinic data, ported from the UI prototype's src/data/*.js.

Dates are relative to "today" (days ago / from now), so the dashboard
always has recent activity whenever the demo is seeded.
"""

from typing import Any

DOCTORS: list[dict[str, Any]] = [
    {
        "key": "rao",
        "full_name": "Dr. Ananya Rao",
        "role": "admin",
        "specialization": "Cardiology",
        "qualification": "MBBS, MD (Cardiology)",
        "registration_number": "TN/MCI/58231",
        "email": "ananya.rao@clinic.in",
        "phone": "+91 98765 10001",
        "accent_color": "#14b8a6",
        "joined_days_ago": 7 * 365,
    },
    {
        "key": "shah",
        "full_name": "Dr. Vikram Shah",
        "role": "doctor",
        "specialization": "General Medicine",
        "qualification": "MBBS, MD (General Medicine)",
        "registration_number": "MH/MCI/44210",
        "email": "vikram.shah@clinic.in",
        "phone": "+91 98765 10002",
        "accent_color": "#3568c9",
        "joined_days_ago": 6 * 365,
    },
    {
        "key": "menon",
        "full_name": "Dr. Priya Menon",
        "role": "doctor",
        "specialization": "Pediatrics",
        "qualification": "MBBS, MD (Pediatrics)",
        "registration_number": "KL/MCI/39876",
        "email": "priya.menon@clinic.in",
        "phone": "+91 98765 10003",
        "accent_color": "#b9791a",
        "joined_days_ago": 5 * 365,
    },
    {
        "key": "nair",
        "full_name": "Dr. Arjun Nair",
        "role": "doctor",
        "specialization": "Orthopedics",
        "qualification": "MBBS, MS (Orthopedics)",
        "registration_number": "KA/MCI/50122",
        "email": "arjun.nair@clinic.in",
        "phone": "+91 98765 10004",
        "accent_color": "#8b5cf6",
        "joined_days_ago": 4 * 365,
    },
    {
        "key": "iyer",
        "full_name": "Dr. Kavya Iyer",
        "role": "doctor",
        "specialization": "Dermatology",
        "qualification": "MBBS, MD (Dermatology)",
        "registration_number": "TN/MCI/61045",
        "email": "kavya.iyer@clinic.in",
        "phone": "+91 98765 10005",
        "accent_color": "#dc4c8c",
        "joined_days_ago": 58,
    },
]


def _p(
    key: str,
    name: str,
    age: int,
    gender: str,
    phone: str,
    address: str,
    blood: str,
    allergies: list[str],
    doctor: str,
    registered_days_ago: int,
) -> dict[str, Any]:
    return {
        "key": key,
        "full_name": name,
        "age": age,
        "gender": gender,
        "phone": phone,
        "address": address,
        "blood_group": blood,
        "allergies": allergies,
        "doctor": doctor,
        "registered_days_ago": registered_days_ago,
    }


PATIENTS: list[dict[str, Any]] = [
    _p("001", "Fathima Begum", 69, "female", "+91 90000 11122", "Anna Nagar, Chennai", "O+", ["NSAIDs"], "rao", 410),
    _p("002", "Suresh Babu", 63, "male", "+91 90000 22233", "T. Nagar, Chennai", "B-", ["Aspirin"], "rao", 300),
    _p("003", "Meena Iyer", 34, "female", "+91 90000 33344", "Mylapore, Chennai", "O+", ["Penicillin"], "rao", 120),
    _p("004", "Ramesh Kumar", 58, "male", "+91 90000 44455", "Andheri, Mumbai", "B+", [], "shah", 260),
    _p("005", "Lakshmi Narayanan", 45, "female", "+91 90000 55566", "Adyar, Chennai", "A+", ["Sulfa drugs"], "rao", 200),
    _p("006", "Arun Prakash", 29, "male", "+91 90000 66677", "Koramangala, Bengaluru", "O-", [], "nair", 40),
    _p("007", "Divya Sundaram", 8, "female", "+91 90000 77788", "Velachery, Chennai", "AB+", ["Dust"], "menon", 150),
    _p("008", "Kavitha Raman", 37, "female", "+91 90000 88899", "Indiranagar, Bengaluru", "A-", [], "iyer", 75),
    _p("009", "Mohammed Iqbal", 51, "male", "+91 90000 99900", "Triplicane, Chennai", "O+", [], "shah", 230),
    _p("010", "Priyanka Das", 26, "female", "+91 90000 10101", "Salt Lake, Kolkata", "B+", ["Latex"], "menon", 20),
    _p("011", "Karthik Subramanian", 41, "male", "+91 90000 12121", "Tambaram, Chennai", "A+", [], "nair", 95),
    _p("012", "Yuvan Shankar", 5, "male", "+91 90000 13131", "Kodambakkam, Chennai", "B+", [], "menon", 60),
]  # fmt: skip


def _rx(name: str, dosage: str, frequency: str, duration: str, instructions: str) -> dict[str, str]:
    return {
        "name": name,
        "dosage": dosage,
        "frequency": frequency,
        "duration": duration,
        "instructions": instructions,
    }


def _v(bp: str, temp: str, pulse: str, weight: str, spo2: str) -> dict[str, str]:
    vitals = {"bp": bp, "temperature": temp, "pulse": pulse, "weight": weight, "spo2": spo2}
    return {k: v for k, v in vitals.items() if v and v != "—"}


# follow_up is in days relative to today: negative = in the past.
VISITS: list[dict[str, Any]] = [
    # Fathima Begum: long-running hypertension management with Dr. Rao
    {"patient": "001", "doctor": "rao", "days_ago": 400, "vitals": _v("156/98", "98.4°F", "84", "61kg", "97%"),
     "complaints": "Occasional headaches, dizziness on standing up.",
     "diagnosis": "Newly diagnosed Essential Hypertension",
     "medicines": [_rx("Amlodipine 5mg", "1-0-0", "Once daily", "30 days", "After breakfast"),
                   _rx("Aspirin 75mg", "0-1-0", "Once daily", "30 days", "After lunch")],
     "advice": "Low-salt diet, daily 20-minute walk. Monitor BP at home twice a week.", "follow_up": -370},
    {"patient": "001", "doctor": "rao", "days_ago": 220, "vitals": _v("142/90", "98.2°F", "80", "62kg", "98%"),
     "complaints": "BP improved, mild ankle swelling in the evenings.",
     "diagnosis": "Hypertension — under control, mild pedal oedema",
     "medicines": [_rx("Amlodipine 5mg", "1-0-0", "Once daily", "30 days", "After breakfast"),
                   _rx("Losartan 50mg", "0-0-1", "Once daily", "30 days", "After dinner")],
     "advice": "Reduce salt further, elevate legs in the evening. Continue home BP log.", "follow_up": -190},
    {"patient": "001", "doctor": "rao", "days_ago": 95, "vitals": _v("134/86", "98.6°F", "78", "61kg", "98%"),
     "complaints": "Feeling well, no headaches. Occasional fatigue.",
     "diagnosis": "Hypertension — well controlled",
     "medicines": [_rx("Amlodipine 5mg", "1-0-0", "Once daily", "60 days", "After breakfast"),
                   _rx("Losartan 50mg", "0-0-1", "Once daily", "60 days", "After dinner"),
                   _rx("Vitamin D3 60000IU", "1 sachet/week", "Once weekly", "8 weeks", "After any meal")],
     "advice": "Continue current medication. Repeat lipid profile before next visit.", "follow_up": -35},
    {"patient": "001", "doctor": "rao", "days_ago": 6, "vitals": _v("130/84", "98.4°F", "76", "60kg", "99%"),
     "complaints": "Routine follow-up. No new complaints.", "diagnosis": "Hypertension — stable",
     "medicines": [_rx("Amlodipine 5mg", "1-0-0", "Once daily", "60 days", "After breakfast"),
                   _rx("Losartan 50mg", "0-0-1", "Once daily", "60 days", "After dinner")],
     "advice": "Continue current medication and lifestyle measures.", "follow_up": 54},
    # Suresh Babu: ischemic heart disease follow-up with Dr. Rao
    {"patient": "002", "doctor": "rao", "days_ago": 280, "vitals": _v("138/88", "98.3°F", "82", "74kg", "97%"),
     "complaints": "Chest tightness on exertion, relieved by rest.",
     "diagnosis": "Stable Angina, likely CAD — referred for ECG & TMT",
     "medicines": [_rx("Aspirin 75mg", "0-1-0", "Once daily", "30 days", "After lunch"),
                   _rx("Atorvastatin 10mg", "0-0-1", "Once daily", "30 days", "After dinner"),
                   _rx("Metoprolol 25mg", "1-0-1", "Twice daily", "30 days", "After food")],
     "advice": "Avoid strenuous exertion until test results reviewed. Get ECG + TMT done.", "follow_up": -260},
    {"patient": "002", "doctor": "rao", "days_ago": 150, "vitals": _v("128/82", "98.2°F", "74", "73kg", "98%"),
     "complaints": "No chest pain since last visit. Occasional breathlessness on stairs.",
     "diagnosis": "CAD — medically managed, stable",
     "medicines": [_rx("Aspirin 75mg", "0-1-0", "Once daily", "60 days", "After lunch"),
                   _rx("Atorvastatin 10mg", "0-0-1", "Once daily", "60 days", "After dinner"),
                   _rx("Metoprolol 25mg", "1-0-1", "Twice daily", "60 days", "After food"),
                   _rx("Clopidogrel 75mg", "0-1-0", "Once daily", "60 days", "After lunch")],
     "advice": "Cardiac rehab walking plan. Recheck lipid profile in 2 months.", "follow_up": -30},
    {"patient": "002", "doctor": "rao", "days_ago": 12, "vitals": _v("124/80", "98.1°F", "72", "72kg", "98%"),
     "complaints": "Feeling much better, walking 30 minutes daily now.",
     "diagnosis": "CAD — stable on current regimen",
     "medicines": [_rx("Aspirin 75mg", "0-1-0", "Once daily", "90 days", "After lunch"),
                   _rx("Atorvastatin 10mg", "0-0-1", "Once daily", "90 days", "After dinner"),
                   _rx("Metoprolol 25mg", "1-0-1", "Twice daily", "90 days", "After food")],
     "advice": "Continue current plan. Annual echo recommended.", "follow_up": 78},
    # Meena Iyer: first seen by Dr. Shah, later referred to Dr. Rao
    {"patient": "003", "doctor": "shah", "days_ago": 110, "vitals": _v("118/76", "100.8°F", "96", "58kg", "97%"),
     "complaints": "Fever with body ache for 2 days, sore throat.", "diagnosis": "Viral Fever",
     "medicines": [_rx("Paracetamol 500mg", "1-1-1", "Three times daily", "4 days", "After food"),
                   _rx("Levocetirizine 5mg", "0-0-1", "Once daily", "4 days", "After dinner"),
                   _rx("ORS Powder", "1 sachet/day", "As needed", "4 days", "In water, sip through the day")],
     "advice": "Plenty of fluids and rest. Return if fever persists beyond 3 days.", "follow_up": -105},
    {"patient": "003", "doctor": "rao", "days_ago": 18, "vitals": _v("122/80", "98.5°F", "102", "59kg", "98%"),
     "complaints": "Occasional palpitations and mild breathlessness, referred by Dr. Shah.",
     "diagnosis": "Palpitations — likely benign, ECG/Holter advised",
     "medicines": [_rx("Metoprolol 25mg", "0-0-1", "Once daily", "15 days", "After dinner"),
                   _rx("Vitamin B12 1500mcg", "1-0-0", "Once daily", "30 days", "After breakfast")],
     "advice": "Avoid caffeine. Get Holter monitoring done before follow-up.", "follow_up": 12},
    # Ramesh Kumar: diabetes management with Dr. Shah
    {"patient": "004", "doctor": "shah", "days_ago": 240, "vitals": _v("132/84", "98.4°F", "78", "82kg", "97%"),
     "complaints": "Increased thirst and frequent urination for 3 weeks.",
     "diagnosis": "Type 2 Diabetes Mellitus, newly diagnosed",
     "medicines": [_rx("Metformin 500mg", "1-0-1", "Twice daily", "30 days", "After food"),
                   _rx("Vitamin D3 60000IU", "1 sachet/week", "Once weekly", "4 weeks", "After any meal")],
     "advice": "Diabetic diet counseling, avoid sugar/refined carbs. Fasting & PP sugar recheck.", "follow_up": -210},
    {"patient": "004", "doctor": "shah", "days_ago": 45, "vitals": _v("128/82", "98.2°F", "76", "80kg", "98%"),
     "complaints": "Sugar levels better controlled, mild tingling in feet.",
     "diagnosis": "T2DM — moderate control, early peripheral neuropathy",
     "medicines": [_rx("Metformin 500mg", "1-0-1", "Twice daily", "60 days", "After food"),
                   _rx("Glimepiride 2mg", "1-0-0", "Once daily", "60 days", "Before breakfast"),
                   _rx("Vitamin B12 1500mcg", "1-0-0", "Once daily", "60 days", "After breakfast")],
     "advice": "Daily foot inspection. HbA1c recheck in 8 weeks.", "follow_up": 15},
    # Lakshmi Narayanan: hypertension with Dr. Rao
    {"patient": "005", "doctor": "rao", "days_ago": 190, "vitals": _v("148/92", "98.3°F", "80", "68kg", "98%"),
     "complaints": "Frequent headaches, neck stiffness.", "diagnosis": "Essential Hypertension",
     "medicines": [_rx("Telmisartan 40mg", "1-0-0", "Once daily", "30 days", "After breakfast"),
                   _rx("Paracetamol 500mg", "1-0-1", "As needed", "5 days", "After food")],
     "advice": "Reduce salt intake, monitor BP weekly.", "follow_up": -160},
    {"patient": "005", "doctor": "rao", "days_ago": 28, "vitals": _v("132/86", "98.2°F", "76", "67kg", "98%"),
     "complaints": "Headaches reduced significantly.", "diagnosis": "Hypertension — improving",
     "medicines": [_rx("Telmisartan 40mg", "1-0-0", "Once daily", "60 days", "After breakfast")],
     "advice": "Continue medication, repeat BP log before next visit.", "follow_up": 32},
    # Arun Prakash: sports injury with Dr. Nair
    {"patient": "006", "doctor": "nair", "days_ago": 9, "vitals": _v("118/74", "98.6°F", "70", "71kg", "99%"),
     "complaints": "Twisted left ankle while playing football, swelling and pain.",
     "diagnosis": "Grade II Ankle Sprain (Left)",
     "medicines": [_rx("Diclofenac 50mg", "1-0-1", "Twice daily", "5 days", "After food"),
                   _rx("Pantoprazole 40mg", "1-0-0", "Once daily", "5 days", "Before breakfast")],
     "advice": "RICE protocol — rest, ice, compression, elevation. Crepe bandage for 1 week. Avoid sports for 3 weeks.",
     "follow_up": 12},
    # Divya Sundaram: pediatric, with Dr. Menon
    {"patient": "007", "doctor": "menon", "days_ago": 140, "vitals": _v("—", "101.2°F", "110", "24kg", "98%"),
     "complaints": "Fever and runny nose for 2 days, decreased appetite.",
     "diagnosis": "Upper Respiratory Tract Infection",
     "medicines": [_rx("Paracetamol Syrup", "5ml", "Three times daily", "3 days", "After food"),
                   _rx("Cetirizine 10mg", "2.5ml", "Once daily", "3 days", "At bedtime")],
     "advice": "Steam inhalation, plenty of fluids. Return if fever exceeds 102°F.", "follow_up": -136},
    {"patient": "007", "doctor": "menon", "days_ago": 21, "vitals": _v("—", "98.4°F", "92", "25kg", "99%"),
     "complaints": "Routine growth & vaccination checkup.",
     "diagnosis": "Healthy — on-track growth, due for booster dose",
     "medicines": [_rx("Multivitamin Syrup", "5ml", "Once daily", "30 days", "After breakfast")],
     "advice": "Booster vaccination scheduled. Continue balanced diet.", "follow_up": 9},
    # Kavitha Raman: dermatology with Dr. Iyer
    {"patient": "008", "doctor": "iyer", "days_ago": 60, "vitals": _v("116/74", "98.4°F", "72", "60kg", "99%"),
     "complaints": "Persistent acne on face and jawline for 2 months.",
     "diagnosis": "Moderate Acne Vulgaris",
     "medicines": [_rx("Clotrimazole Cream", "Thin layer", "Twice daily", "3 weeks", "Cleanse before applying"),
                   _rx("Doxycycline 100mg", "0-0-1", "Once daily", "3 weeks", "After dinner")],
     "advice": "Gentle non-comedogenic cleanser, avoid oily cosmetics, use sunscreen daily.", "follow_up": -25},
    {"patient": "008", "doctor": "iyer", "days_ago": 25, "vitals": _v("118/76", "98.3°F", "70", "60kg", "99%"),
     "complaints": "Visible improvement, occasional new breakouts before periods.",
     "diagnosis": "Acne Vulgaris — improving",
     "medicines": [_rx("Clotrimazole Cream", "Thin layer", "Once daily", "4 weeks", "At night")],
     "advice": "Continue skincare routine, follow up if new flare-ups occur.", "follow_up": 35},
    # Mohammed Iqbal: diabetes + hypertension with Dr. Shah
    {"patient": "009", "doctor": "shah", "days_ago": 200, "vitals": _v("144/92", "98.5°F", "84", "88kg", "96%"),
     "complaints": "Fatigue, blurred vision occasionally, known diabetic for 5 years.",
     "diagnosis": "T2DM with Hypertension — suboptimal control",
     "medicines": [_rx("Metformin 500mg", "1-0-1", "Twice daily", "30 days", "After food"),
                   _rx("Amlodipine 5mg", "1-0-0", "Once daily", "30 days", "After breakfast"),
                   _rx("Atorvastatin 10mg", "0-0-1", "Once daily", "30 days", "After dinner")],
     "advice": "Strict diet control, home glucose + BP monitoring log.", "follow_up": -170},
    {"patient": "009", "doctor": "shah", "days_ago": 15, "vitals": _v("130/84", "98.4°F", "78", "85kg", "97%"),
     "complaints": "Feeling better overall, sugar and BP logs improved.",
     "diagnosis": "T2DM with Hypertension — improving control",
     "medicines": [_rx("Metformin 500mg", "1-0-1", "Twice daily", "60 days", "After food"),
                   _rx("Amlodipine 5mg", "1-0-0", "Once daily", "60 days", "After breakfast")],
     "advice": "Continue lifestyle changes. HbA1c and lipid profile before next visit.", "follow_up": 45},
    # Priyanka Das: allergic reaction with Dr. Menon
    {"patient": "010", "doctor": "menon", "days_ago": 19, "vitals": _v("110/70", "99.1°F", "88", "54kg", "98%"),
     "complaints": "Skin rash and itching after using latex gloves at work.",
     "diagnosis": "Allergic Contact Dermatitis (Latex)",
     "medicines": [_rx("Levocetirizine 5mg", "0-0-1", "Once daily", "7 days", "After dinner"),
                   _rx("Hydrocortisone Cream 1%", "Thin layer", "Twice daily", "7 days", "On affected area")],
     "advice": "Avoid latex contact, switch to nitrile gloves. Return if rash spreads.", "follow_up": 11},
    # Karthik Subramanian: lower back pain with Dr. Nair
    {"patient": "011", "doctor": "nair", "days_ago": 80, "vitals": _v("124/80", "98.4°F", "74", "79kg", "98%"),
     "complaints": "Lower back pain for 2 weeks, worse after long sitting.",
     "diagnosis": "Mechanical Low Back Pain",
     "medicines": [_rx("Diclofenac 50mg", "1-0-1", "Twice daily", "5 days", "After food"),
                   _rx("Pantoprazole 40mg", "1-0-0", "Once daily", "5 days", "Before breakfast")],
     "advice": "Physiotherapy referral, ergonomic chair, avoid heavy lifting.", "follow_up": -50},
    {"patient": "011", "doctor": "nair", "days_ago": 50, "vitals": _v("120/78", "98.2°F", "72", "78kg", "99%"),
     "complaints": "Pain reduced by 80%, occasional stiffness in the morning.",
     "diagnosis": "Low Back Pain — resolving",
     "medicines": [_rx("Diclofenac 50mg", "1-0-1", "As needed", "5 days", "After food")],
     "advice": "Continue physiotherapy exercises, maintain posture breaks every hour.", "follow_up": 60},
    # Yuvan Shankar: pediatric, with Dr. Menon
    {"patient": "012", "doctor": "menon", "days_ago": 55, "vitals": _v("—", "100.4°F", "104", "17kg", "98%"),
     "complaints": "Cough and cold for 3 days, mild fever at night.", "diagnosis": "Common Cold",
     "medicines": [_rx("Paracetamol Syrup", "5ml", "As needed for fever", "3 days", "After food"),
                   _rx("ORS Powder", "1 sachet/day", "As needed", "3 days", "In water, sip through the day")],
     "advice": "Warm fluids, steam inhalation, rest. Return if breathing difficulty.", "follow_up": -51},
    {"patient": "012", "doctor": "menon", "days_ago": 3, "vitals": _v("—", "98.6°F", "90", "18kg", "99%"),
     "complaints": "Routine growth checkup, parents report good appetite.",
     "diagnosis": "Healthy — normal growth for age",
     "medicines": [_rx("Multivitamin Syrup", "5ml", "Once daily", "30 days", "After breakfast")],
     "advice": "Continue balanced diet, outdoor playtime encouraged.", "follow_up": 87},
    # Today's walk-ins
    {"patient": "003", "doctor": "shah", "days_ago": 0, "vitals": _v("116/76", "101.4°F", "98", "58kg", "97%"),
     "complaints": "Sudden onset fever with chills since this morning, mild body ache.",
     "diagnosis": "Acute Viral Fever",
     "medicines": [_rx("Paracetamol 500mg", "1-1-1", "Three times daily", "4 days", "After food"),
                   _rx("ORS Powder", "1 sachet/day", "As needed", "4 days", "In water, sip through the day")],
     "advice": "Rest and hydration. Return if fever crosses 102°F or persists beyond 3 days.", "follow_up": 4},
    {"patient": "006", "doctor": "nair", "days_ago": 0, "vitals": _v("120/78", "98.4°F", "72", "71kg", "99%"),
     "complaints": "Follow-up for ankle sprain — swelling gone, mild stiffness only.",
     "diagnosis": "Ankle Sprain — recovered",
     "medicines": [_rx("Diclofenac 50mg", "1-0-1", "As needed", "3 days", "After food")],
     "advice": "Cleared for light training. Resume full sport activity gradually over 2 weeks.", "follow_up": 21},
]  # fmt: skip

# (doctor key, days ago)
LOGINS: list[tuple[str, int]] = [("rao", 0), ("shah", 1), ("menon", 1), ("nair", 3), ("iyer", 6)]
